### ISSUE TITLE
What other implementations of BLS12-381 are there to test against?

### ISSUE THREAD

**Issue by ChristopherA** [Chia-Network/bls-signatures#10]
Who else is using, or plans to use BLS12-381? What platforms and languages? Where are the test vectors? If any, they should probably be listed in README.md

**Comment by jonspock** [comment]
See here: https://ethresear.ch/t/pragmatic-signature-aggregation-with-bls/2105
Supposedly both ETH & Zcash

**Comment by zmanian** [comment]
We are planning to adopt BLS12_381 for consensus in a future version of Tendermint and maybe for user accounts

**Comment by mariano54** [comment]
Just added a python implementation that follows relic. Will be adding test vectors soon, along with a simple spec. Also, I'm interested in the Fouque and Tibouchi hashing to g2 method, although relic doesn't have it at this point.

**Comment by mariano54** [comment]
Test vectors, spec, and Fouque-Tibouchi have been been merged to master. This one doesn't conform to any of the other libraries due to g1 and g2 being flipped, but also there are some slight differences in hashing, and other area.

**Comment by mariano54** [comment]
Other libraries to checkout out: 

- BGLS in go (https://github.com/Project-Arda/bgls)
- herumi bls in c++ (https://github.com/herumi/bls)
- zcash bls in rust (https://github.com/str4d/bls)
