### ISSUE TITLE
Ubuntu18.04 cannot cmake

### ISSUE THREAD

**Issue by Winter95** [Chia-Network/bls-signatures#109]
![image](https://user-images.githubusercontent.com/31640814/82109549-86f84800-9769-11ea-9b52-6329f08e0366.png)

**Comment by hoffmang9** [comment]
the command after `cd build` is `cmake ../`

**Comment by Winter95** [comment]
I hava run the command  cmake ../ .After that ,it have some error.
![image](https://user-images.githubusercontent.com/31640814/82109879-2d454d00-976c-11ea-9fe0-ad0938861dce.png)

**Comment by hoffmang9** [comment]
The error is from when you ran cmake - above that screenshot.

**Comment by Winter95** [comment]
I hava run the command cmake ../ .After that ,when I ran cmake --build . -- -j 6 ,it have some error.Is there anything you need to add to run it? Is there anything you need to add to run it(cmake --build . -- -j 6)? Thank you for your answer.

**Comment by hoffmang9** [comment]
what was the error you received when you ran `cmake ../`?

**Comment by Winter95** [comment]
sorry i see it 
![image](https://user-images.githubusercontent.com/31640814/82110406-e73eb800-9770-11ea-9f8c-092587688937.png)

**Comment by hoffmang9** [comment]
You likely did not run `git submodule update --init --recursive` from the root of the project folder.

Also you can run `sudo apt-get install -y doxygen` to fix the doxygen warning.

**Comment by Winter95** [comment]
Thank you very much！
![image](https://user-images.githubusercontent.com/31640814/82168245-e92f8500-98f0-11ea-81a2-b7de39607059.png)
Experimental results the first set of data shows that the time of 1000 signatures is 2000 milliseconds, and the time of one signature is only 2 milliseconds?Does this time include initialization?Desides，Does the second set of data indicate that the verification time for 1000 signatures is 4191 milliseconds, and the verification time for a signature is only 0.491 milliseconds?And does the fifth set of data mean that it only takes 277 milliseconds to aggregate the signatures of 1,000 identical messages?Other instructions are similar.The project was really great!There's a lot to learn.
