### ISSUE TITLE
Relic_conf.h: No such file or directory

### ISSUE THREAD

**Issue by igorperazzoli** [Chia-Network/bls-signatures#113]
When I try to run the code in which the library is included, this error appears and I haven't found this file anywhere else, does anyone know how to solve it?
![Erro](https://user-images.githubusercontent.com/40304622/82387301-06f20c80-9a0d-11ea-8452-d0db15f7d4fd.png)

**Comment by wjblanke** [comment]
If you run cmake . from the root bls-signatures folder it should eventually run cmake on relic in contrib which will create relic_conf.h
