### ISSUE TITLE
DSEED or SEED

### ISSUE THREAD

**Issue by alinush** [Chia-Network/bls-signatures#114]
On [line 56 of CMakeLists.txt](https://github.com/Chia-Network/bls-signatures/blob/523738e4b8ec1faf0d9f620eed494eb68f3dd516/CMakeLists.txt#L56) there's a variable named `DSEED` rather than `SEED`, which is what RELIC actually needs.

Is this a mistake/typo? Or is this `DSEED` define meant to be used by other dependencies?

This is strange because, [on line 59](https://github.com/Chia-Network/bls-signatures/blob/523738e4b8ec1faf0d9f620eed494eb68f3dd516/CMakeLists.txt#L59), you use the correct variable `SEED`.

**Comment by mariano54** [comment]
Looks like a typo, thanks for pointing it out

**Comment by hoffmang9** [comment]
Finally fixed and thanks - https://github.com/Chia-Network/bls-signatures/pull/145
