### ISSUE TITLE
build with shared with libsodium & libgmp

### ISSUE THREAD

**Issue by paizzj** [Chia-Network/bls-signatures#130]
now, the bls-signature build with static linking with libsodium & libgmp.
the CmakeList can't support build shared with libsodium&libgm.
we need set  :
set(sodium_USE_STATIC_LIBS FALSE) 
set(gmp_USE_STATIC_LIBS FALSE)

**Comment by hoffmang9** [comment]
This PR reverts to defaulting to dynamic libsodium - https://github.com/Chia-Network/bls-signatures/pull/145
