### ISSUE TITLE
Rule of 5

### ISSUE THREAD

**Issue by shasha94** [Chia-Network/bls-signatures#131]
I tried using  the class bls::PrivateKey, using this simple code:
bls::PrivateKey a= ...some initialization...;
bls::PrivateKey b= ...some initialization...;
a=b;

This didn't compile due to the class not complying with the rule of 5 [https://en.cppreference.com/w/cpp/language/rule_of_three] .
The class defines a copy and move constructor but not copy and move assignment operator. 

Any reason for that?

**Comment by mariano54** [comment]
It's not consistent, I had not realized. I would like to undefine the copy and move constructor to prevent copying.

**Comment by shasha94** [comment]
I agree that it might be preferable to not copy private keys so it will not be stored in a lot of places in the ram.

However, having a working move constructor and move assignment is always very recommanded.
Think that without move constructor, it is impossible even to return the type  bls::PrivateKey from a function (when ignoring copy elision).
I don't know a single class (which is not a singleton) that deleted both the copy and move constructor.
