### ISSUE TITLE
`hash(g1_element)` doesn't work as expected

### ISSUE THREAD

**Issue by richardkiss** [Chia-Network/bls-signatures#134]
```
>>> import blspy
>>> hash(blspy.G1Element.generator() * 5)
272913899
>>> hash(blspy.G1Element.generator() * 5)
272913883
>>> 
```

The hash value should be based on something that never changes.

Without this property, `G1Element` can't be used as a dictionary key. One workaround is to use `bytes(g1_element)`, but that's rather ugly.

**Comment by mariano54** [comment]
Yeah agreed, this would be a good change to blspy

**Comment by richardkiss** [comment]
Bump
