### ISSUE TITLE
Using G1 as signature

### ISSUE THREAD

**Issue by themantre** [Chia-Network/bls-signatures#162]
This library uses minimum public key sizes (MPL). A G2Element is a signature (96 bytes), and a G1Element is a public key (48 bytes).

Is it possible to use G1Element (48 bytes) as signature?

**Comment by mariano54** [comment]
It's not possible using the current api, you would need to add additional methods to support that. It would not be a huge amount of work though, as it's mostly the same but reversed.

**Comment by mircial** [comment]
@themantre hi, do you know how to use G1Element (48 bytes) as signature?
