### ISSUE TITLE
Compiler Error on Ubuntu Bionic release

### ISSUE THREAD

**Issue by jonspock** [Chia-Network/bls-signatures#2]
CCLD     librdrand.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     libsodium.la
crypto_stream/salsa20/xmm6/.libs/libsodium_la-salsa20_xmm6-asm.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status

Looks like various binary files from a different distribution were tarred up in the libsodium file
Clean download of libsodium from github doesn't have this issue

**Comment by mariano54** [comment]
Thanks for the tip, just uploaded the clean version from github. Were you able to build apart from that?

**Comment by jonspock** [comment]
On MacOS yes, but got a C++ compiler error on Bionic. Will upload later. Thanks
