### ISSUE TITLE
Failed to verify signature

### ISSUE THREAD

**Issue by zycChun** [Chia-Network/bls-signatures#208]
```
    vector<uint8_t> seed = {0,  50, 6,  244, 24,  199, 1,  25,  52,  88,  192,
                            19, 18, 12, 89,  6,   220, 18, 102, 58,  209, 82,
                            12, 62, 89, 110, 182, 9,   44, 20,  254, 22};

    PrivateKey sk = AugSchemeMPL().KeyGen(seed);
    G1Element pk = sk.GetG1Element();

    vector<uint8_t> message = {1, 2, 3, 4, 5};
    G2Element signature = AugSchemeMPL().Sign(sk, message);

    // Verify the signature
    bool ok = AugSchemeMPL().Verify(pk, message, signature);
```

**Comment by mariano54** [comment]
Can you print the sk, pk and signature? I just tried using blspy and it verified correctly.
sk: `<PrivateKey 377091f0e728463bc2da7d546c53b9f6b81df4a1cc1ab5bf29c5908b7151a32d>`
sig: `<G2Element b00ab9a8af54804b43067531d96c176710c05980fccf8eee1ae12a4fd543df929cce860273af931fe4fdbc407d495f73114ab7d17ef08922e56625daada0497582340ecde841a9e997f2f557653c21c070119662dd2efa47e2d6c5e2de00eefa>`
pk: `<G1Element 86243290bbcbfd9ae75bdece7981965350208eb5e99b04d5cd24e955ada961f8c0a162dee740be7bdc6c3c0613ba2eb1>`

**Comment by zycChun** [comment]
I am using Xcode
<img width="476" alt="截屏2021-04-22 下午4 53 49" src="https://user-images.githubusercontent.com/39869163/115686427-c1ac2c80-a38b-11eb-8f85-ee52600cebba.png">
<img width="253" alt="截屏2021-04-22 下午4 54 28" src="https://user-images.githubusercontent.com/39869163/115686431-c2dd5980-a38b-11eb-8f11-c86c3558033a.png">

**Comment by arvidn** [comment]
that program works for me too. on MacOS.

@zycChun make sure you're building the library and your client correctly, and that your client is linking against the correct library at run-time.

**Comment by mariano54** [comment]
Also could you provide info on the version of macos, cpu, and xcode version that you used?

**Comment by zycChun** [comment]
I found the problem, it was a problem with the static library I synthesized.
thank you very much!
