### ISSUE TITLE
Xcode compile static library

### ISSUE THREAD

**Issue by huomeina** [Chia-Network/bls-signatures#210]
Xcode compile librelic_ios.a static library x86_64 can compile successfully, arm64 environment compile error.
Both the libblstmp_ios.a and libbls_ios.a environments can succeed.

![1619165168614_52C10748-AC0A-454B-B024-0FE54228F7A0](https://user-images.githubusercontent.com/4144117/115840430-41023480-a44e-11eb-8322-5bbd7f125afc.png)

How should I compile the ios static library used by Xcode?

**Comment by emlowe** [comment]
Currently iOS is not an officially supported platform - community PRs are welcome
