### ISSUE TITLE
Different from eip-2333

### ISSUE THREAD

**Issue by vae520283995** [Chia-Network/bls-signatures#216]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2333.md#test-cases
seed = 0x3141592653589793238462643383279502884197169399375105820974944592
master_SK = 29757020647961307431480504535336562678282505419141012933316116377660817309383
child_index = 3141592653
child_SK = 25457201688850691947727629385191704516744796114925897962676248250929345014287

https://github.com/Chia-Network/bls-signatures/blob/7cc5ae144cb2a4e54f812b1aeaaa673fbb068ac5/src/test.cpp#L222
TestEIP2333("3141592653589793238462643383279502884197169399375105820974944592",
// 36167147331491996618072159372207345412841461318189449162487002442599770291484
"4ff5e145590ed7b71e577bb04032396d1619ff41cb4e350053ed2dce8d1efd1c",
// 41787458189896526028601807066547832426569899195138584349427756863968330588237
"5c62dcf9654481292aafa3348f1d1b0017bbfb44d6881d26d2b17836b38f204d",
3141592653
);

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2333.md#procedure-2
1. salt = "BLS-SIG-KEYGEN-SALT-"
2. SK = 0
3. while SK == 0:
4.     salt = H(salt)
5.     PRK = HKDF-Extract(salt, IKM || I2OSP(0, 1))
6.     OKM = HKDF-Expand(PRK, key_info || I2OSP(L, 2), L)
7.     SK = OS2IP(OKM) mod r
8. return SK

eip-2333 has one more line of code than https://github.com/Chia-Network/bls-signatures
line 4

**Comment by hoffmang9** [comment]
The EIP changed after we went shipped the final version of BLS that locks in our plot format. Key encryption will be at a higher level in the application.

**Comment by vae520283995** [comment]
> The EIP changed after we shipped the final version of BLS that locks in our plot format. Key encryption will be at a higher level in the application.

Thank you for your answer, will you modify the library implementation to eip-2333 in the future?

**Comment by hoffmang9** [comment]
We can not as it would invalidate plots.

**Comment by vae520283995** [comment]
> We can not as it would invalidate plots.

Can I understand, I should write two key derivation programs for eth2 and chia respectively？

**Comment by hoffmang9** [comment]
I believe you can just leave the salt empty for Chia. @mariano54 May be able to comment.
