### ISSUE TITLE
G1Element FromBytes err

### ISSUE THREAD

**Issue by 200787128** [Chia-Network/bls-signatures#218]
G1Element FromBytes

g1_read_bin(ele.p, buffer, G1Element::SIZE + 1);
G1Element::SIZE  = 48

g1_read_bin=ep_read_bin()
if (len != (RLC_FP_BYTES + 1) && len != (2 * RLC_FP_BYTES + 1)) {
		RLC_THROW(ERR_NO_BUFFER);
		return;
	}

len=33 or 65
!= 49
RLC_THROW why??

**Comment by blawar** [comment]
it is failing here: https://github.com/relic-toolkit/relic/blob/main/src/ep/relic_ep_util.c#L249

```
#define RLC_FP_BYTES 	((int)RLC_CEIL(RLC_FP_BITS, 8))

#define RLC_CEIL(A, B)			(((A) - 1) / (B) + 1)

#define RLC_FP_BITS 	((int)FP_PRIME)
```

relic_conf.h defaults FP_PRIME = 256

the public keys used here are 384bits, not 256.  so it may be possible to fix this by recompiling/reconfiguring relic with a different size.

**Comment by blawar** [comment]
Look at preset/x64-pbc-bls12-381.sh

**Comment by 200787128** [comment]
thanks you set FP_PRIME = 381 is ok
