### ISSUE TITLE
Is there a java version of bls12-381?

### ISSUE THREAD

**Issue by lh232510** [Chia-Network/bls-signatures#219]

**Comment by hoffmang9** [comment]
JavaScript bindings are included and were updated a couple of weeks ago to be current. They are being built and tested by the CI and I point you there as the README may be slightly out of date.

**Comment by lh232510** [comment]
I mean Java, not JavaScript!

**Comment by hoffmang9** [comment]
No.

**Comment by BekzhanOmirzak** [comment]
Did you find the java version of this library?
