### ISSUE TITLE
Build fails when GMP_NAME is found to be a shared lib `*.so` file

### ISSUE THREAD

**Issue by madMAx43v3r** [Chia-Network/bls-signatures#225]
See: https://github.com/Chia-Network/bls-signatures/blob/4e21aa6742d67562920ac67507e90b722116b14b/src/CMakeLists.txt#L56

```
[ 96%] Linking C static library ../lib/librelic_s.a
[ 96%] Built target relic_s
Scanning dependencies of target combined_custom
Scanning dependencies of target runbench
/bin/ar: /usr/lib64/libgmp.so: File format not recognized
make[2]: *** [lib/bls-signatures/src/CMakeFiles/combined_custom.dir/build.make:79: lib/bls-signatures/src/CMakeFiles/combined_custom] Error 1
make[1]: *** [CMakeFiles/Makefile2:537: lib/bls-signatures/src/CMakeFiles/combined_custom.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by xorinox** [comment]
Issue was already brought up in 2019 and then closed :(   https://github.com/Chia-Network/bls-signatures/issues/68

**Comment by xorinox** [comment]
On Fedora 33 Server I installed the static versions of the libs gmp and sodium:
`sudo yum install libsodium-static.i686 gmp-static.i686`

After that I could compile bls-signatures as per readme without issues.
