### ISSUE TITLE
wont build on cent os 7 or 8

### ISSUE THREAD

**Issue by we-sell-bags** [Chia-Network/bls-signatures#226]
-- Configured operating system: LINUX
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configured GMP: /usr/lib64/libgmp.so
-- Compiler flags: -m64 -Wall   -O3 -funroll-loops -fomit-frame-pointer -pthread
-- Linker flags: -L/home/chia/bls-signatures/build/_deps/relic-src/src/low/gmp/ 
-- Configured /home/chia/bls-signatures/build/_deps/relic-src/include/relic_conf.h.in
SODIUM_FOUND in src/CMakeLists.txt
-- pybind11 v2.6.2 
-- Found PythonInterp: /usr/local/bin/python3.9 (found version "3.9.5") 
-- Found PythonLibs: /usr/local/lib/libpython3.9.a
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chia/bls-signatures/build`

 cmake --build . -- -j 6

[ 96%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/low/gmp/relic_fb_shift_low.c.o
[ 96%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/low/easy/relic_fb_slv_low.c.o
[ 96%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/low/easy/relic_fb_sqr_low.c.o
[ 97%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/low/easy/relic_fb_srt_low.c.o
[ 97%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/low/easy/relic_fb_trc_low.c.o
[ 98%] Linking C static library ../lib/librelic_s.a
[ 98%] Built target relic_s
[ 98%] Building CXX object src/CMakeFiles/runbench.dir/test-bench.cpp.o
[ 99%] Building CXX object python-bindings/CMakeFiles/blspy.dir/pythonbindings.cpp.o
/opt/rh/devtoolset-10/root/usr/bin/ar: /usr/lib64/libgmp.so: file format not recognized
gmake[2]: *** [src/CMakeFiles/combined_custom.dir/build.make:73: src/CMakeFiles/combined_custom] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:199: src/CMakeFiles/combined_custom.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable runbench
'

**Comment by xorinox** [comment]
Suggested a workaround in https://github.com/Chia-Network/bls-signatures/issues/225   might work for Centos 7/8 also.

**Comment by emlowe** [comment]
Centos 7 the default compiler is GCC 4.8.5 which is not C++17 compliant. The easiest is to install devtoolset-7 (or later). You will need to make sure to set the CXX and CC environment variables so cmake will pick up the correct compiler. So

``` 
scl enable devtoolset-7 bash
export CXX=`which g++`
export CC=`which gcc`
```

For both Centos7 and Centos8 you likely need to install the static GMP and libsodium libraries, as by default the build process will find and try to use the dynamic ones

```sudo yum install libsodium-static gmp-static```
