### ISSUE TITLE
Conflict with ChainCode class when used in Bitcoin based code

### ISSUE THREAD

**Issue by codablock** [Chia-Network/bls-signatures#23]
The ChainCode class conflicts with https://github.com/bitcoin/bitcoin/blob/master/src/pubkey.h#L27 when used in Bitcoin based code (Dash in my case).

I assume others will encounter this problem as well in the future. Possible fix is to either rename ChainCode to something else or wrap everything from this library into its own namespace. IMHO, using a namespace would be the better solution.

**Comment by mariano54** [comment]
I agree namespace is better, but also this ChainCode is supposed to replace that one (along with pubkeys, private keys, etc). If I were integrating this into Bitcoin, I would prefer to have only one ChainCode.

**Comment by codablock** [comment]
It depends on how far someone would go with integrating this into a Bitcoin-like coin. Dash (which I'm working for) for example, will only use BLS for Dash-only related features in the beginning (having it in transactions is for the far future), so we'd like to avoid leaking library details into places which don't have a dependency on the library yet.

**Comment by mariano54** [comment]
OK makes sense. I will close this for now.
