### ISSUE TITLE
Stil getting blake2.h alignment errors and unable to build on fedora 34 w. gcc11

### ISSUE THREAD

**Issue by ckti** [Chia-Network/bls-signatures#232]
```
cmake --version
cmake version 3.20.3

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.1.1-20210428/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.1 20210428 (Red Hat 11.1.1-1) (GCC) 
```
git clone https://github.com/Chia-Network/bls-signatures.git
cd bls-signatures/
mkdir build
cd build
cmake ../
cmake --build . -- -j 1
[  0%] Built target arith_objs
Consolidate compiler generated dependencies of target relic_s
[  0%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/md/blake2s-ref.c.o
In file included from /home/ckti/bls-signatures/build/_deps/relic-src/src/md/blake2s-ref.c:18:
/home/ckti/bls-signatures/build/_deps/relic-src/src/md/blake2.h:101:5: error: size of array element is not a multiple of its alignment
  101 |     blake2s_state S[8][1];
      |     ^~~~~~~~~~~~~
/home/ckti/bls-signatures/build/_deps/relic-src/src/md/blake2.h:102:5: error: size of array element is not a multiple of its alignment
  102 |     blake2s_state R[1];
      |     ^~~~~~~~~~~~~
/home/ckti/bls-signatures/build/_deps/relic-src/src/md/blake2.h:109:5: error: size of array element is not a multiple of its alignment
  109 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
/home/ckti/bls-signatures/build/_deps/relic-src/src/md/blake2.h:110:5: error: size of array element is not a multiple of its alignment
  110 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
/home/ckti/bls-signatures/build/_deps/relic-src/src/md/blake2s-ref.c: In function ‘blake2s’:
/home/ckti/bls-signatures/build/_deps/relic-src/src/md/blake2s-ref.c:329:3: error: size of array element is not a multiple of its alignment
  329 |   blake2s_state S[1];
      |   ^~~~~~~~~~~~~
gmake[2]: *** [_deps/relic-build/src/CMakeFiles/relic_s.dir/build.make:2834: _deps/relic-build/src/CMakeFiles/relic_s.dir/md/blake2s-ref.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:306: _deps/relic-build/src/CMakeFiles/relic_s.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by emlowe** [comment]
Unfortunately, the default revision of relic pulled in during cmake has this bug (1885ae3b681c423c72b65ce1fe70910142cf941c) - However, you can force it to pull in relic_main, which I think would work, but I have not tested. Try setting RELIC_MAIN=yes environment variable before running cmake. This should cause cmake to fetch the head of the main branch for relic.

**Comment by emlowe** [comment]
I will confirm that setting RELIC_MAIN=yes before running cmake results in a successful build and runtests pass. So on a typical command line that would be RELIC_MAIN=yes cmake ..
Closing issue
