### ISSUE TITLE
32 bit build on 64 bit arch fails (produces 64 bit objects)

### ISSUE THREAD

**Issue by guidovranken** [Chia-Network/bls-signatures#255]
On x64, `CFLAGS` set to `-m32`, using this cmake command:

```
cmake .. -DBUILD_BLS_PYTHON_BINDINGS=0 -DBUILD_BLS_TESTS=0 -DBUILD_BLS_BENCHMARKS=0 -DARCH=X86
```

Produces 64 bit Relic objects (should be 32 bit). I also tried prefixing the `cmake` command with `setarch i386` to no avail.

I didn't do a full bisect but at https://github.com/Chia-Network/bls-signatures/commit/7457c4bdc0991c8911f725d32459d7f0b0b730c3 it still produced 32 bit objects, as it should.

CC @dfaranha though I don't know if this is a bug in `bls-signatures` or in `relic`

Even if `bls-signatures` is not used on 32 bit archictectures (I don't know if it is), it's still useful to have a working 32 bit build in the interest of fuzzing (occasionally fuzzing finds bugs in 32 bit targets which may also affect 64 bit targets).

**Comment by dfaranha** [comment]
I just did a build of RELIC with just -DARCH=X86 and got 32-bit binaries.

**Comment by emlowe** [comment]
You can build 32-bit bls-signatures on a 32-bit machine. I previously tested this with 32-bit centos 7 OS

**Comment by guidovranken** [comment]
I couldn't get it to work and have disabled the 32 bit build for Chia on OSS-Fuzz: https://github.com/google/oss-fuzz/pull/6218

If anyone else wants to give it a try then go ahead otherwise you can close this issue.
