### ISSUE TITLE
CFlags being overriden instead of concatenated

### ISSUE THREAD

**Issue by sidhujag** [Chia-Network/bls-signatures#267]
Hi Guys,

It seems you guys are overriding CFLAGS which means any other flags passed in will be removed:

https://github.com/Chia-Network/bls-signatures/blob/ecf77cc9a74594e7445a27cce17d9a7f734b601f/CMakeLists.txt#L92

It should be 

``set(CFLAGS "${CFLAGS} -O3 -funroll-loops -fomit-frame-pointer" CACHE STRING "")`` I guess. Or you can check out what Relic is doing here: https://github.com/relic-toolkit/relic/blob/main/CMakeLists.txt#L230

**Comment by AmineKhaldi** [comment]
Hi jagdeep,

Please note that `CFLAGS` in this context is not the environment variable that controls the C compiler flags, it's just a CMake variable that happens, in this particular case, to control an option in the Relic library's build.
You can see that they build up on this option and eventually concatenate the CMake variable that controls C compiler flags: `CMAKE_C_FLAGS` just some lines below the line you kindly highlighted (line 297).

I hope this helps!

**Comment by sidhujag** [comment]
Unfortunately its not a controlled variable, its part of CMake

https://cmake.org/cmake/help/latest/envvar/CFLAGS.html

It will be picked up from ENV and so its hard to pass in custom CFLAGS this assumed that CFLAGS will not be set by the build system. In our case CFLAGS is always set and so these flags "-funroll-loops -fomit-frame-pointer" are never set in relic.

**Comment by AmineKhaldi** [comment]
Hmm, the problem is, Relic are using this (see 2f451f7 on this side to accommodate for that) when IMHO they shouldn't. This names clash (and proper flags handling in general) could be fixed on Relic's side, eliminating the need to alter CFLAGS on this side at all, as CMake already initializes CMAKE_C_FLAGS from CFLAGS.

I can send a PR to them suggesting a rename to COMP_FLAGS or any other name they see fit, if you find the above reasonable.

**Comment by wjblanke** [comment]
We can use a Chia fork (the same as the PR) of Relic until Relic upstreams it

**Comment by sidhujag** [comment]
> Hmm, the problem is, Relic are using this (see [2f451f7](https://github.com/Chia-Network/bls-signatures/commit/2f451f7afd17c7aa7534d3483e39ac351993fe19) on this side to accommodate for that) when IMHO they shouldn't. This names clash (and proper flags handling in general) could be fixed on Relic's side, eliminating the need to alter CFLAGS on this side at all, as CMake already initializes CMAKE_C_FLAGS from CFLAGS.
> 
> I can send a PR to them suggesting a rename to COMP_FLAGS or any other name they see fit, if you find the above reasonable.

Well you can also just append CFLAGS so when it gets to relic it will set it to what you need. Why do you need to set anyway? Relic seems to be setting the same ones (O2 not O3, O3 is not as safe and sometimes ends up slower is there a reason to use O3 optimization anyway)? 

Relic appends if ENV sets, otherwise just sets it, it so I don't see how its an issue upstream

**Comment by AmineKhaldi** [comment]
@sidhujag
Could you please test 667afa6 with `COMP_FLAGS`? Thanks.

**Comment by sidhujag** [comment]
> @sidhujag
> Could you please test [667afa6](https://github.com/Chia-Network/bls-signatures/commit/667afa6c00af670e2fb4226f163ce56ab056a7ce) with `COMP_FLAGS`? Thanks.

what specifically is needing to be set by your library that isn't set by relic upstream anyway? Why do you need to set these flags because most if not all are set upstream?

**Comment by dfaranha** [comment]
Hi, I don't understand why it should be changed at RELIC's side. The current handling is just to make it more convenient to change CFLAGS for different builds in comparison to changing CMAKE_C_FLAGS, something I do quite frequently when benchmarking.

This should not affect any projects outside RELIC, but please enlighten me if I got this wrong.
