### ISSUE TITLE
Cannot read property 'key_gen' of undefined

### ISSUE THREAD

**Issue by Rasika9596** [Chia-Network/bls-signatures#285]
Hello,

I've installed bls-signatures using 'npm i bls-signatures --save' and using the below code,

```
const loadBls = require("bls-signatures");
 const BLS = await loadBls();
    var seed = Uint8Array.from([
      0, 50, 6, 244, 24, 199, 1, 25, 52, 88, 192, 19, 18, 12, 89, 6, 220, 18,
      102, 58, 209, 82, 12, 62, 89, 110, 182, 9, 44, 20, 254, 22,
    ]);
    var sk = BLS.AugSchemeMPL.key_gen(seed);
    console.log(sk);
    var pk = sk.get_g1();
    console.log(pk);
```

But I'm getting this error,

![image](https://user-images.githubusercontent.com/61308915/135980489-844cfe15-d2d8-4a92-b7bf-17696e897aba.png)

package.json,

![image](https://user-images.githubusercontent.com/61308915/135980582-6df3f116-0a6c-4c15-b547-1ceb3a0149eb.png)

Could anyone please help here?

**Comment by hoffmang9** [comment]
The version on npm is quite out of date and we are attempting to rectify that. The version direct from this repository is what you should use.

**Comment by Rasika9596** [comment]
Thank you so much! I'll give it a try and get back.
