### ISSUE TITLE
[Bug] blspy fails to build due to MINSIGSTKSZ no longer being a compile-time constant

### ISSUE THREAD

**Issue by llowrey** [Chia-Network/bls-signatures#290]
### What happened?

I cloned chia-blockchain and attempted to build per standard procedure, which I have done successfully many times before. My one Fedora 35 host is not able to build successfully due to MINSIGSTKSZ no longer being a compile-time constant. Search results indicate that this is due to the version of glibc included with Fedora 35.

OS: Fedora 35
glibc: 2.34

``` In file included from /usr/include/signal.h:328,
                   from /tmp/pip-install-_7kaglg9/blspy_df253f728ad84f1d9b0290f4d0ec90ab/src/../contrib/catch/catch.hpp:8034,
                   from /tmp/pip-install-_7kaglg9/blspy_df253f728ad84f1d9b0290f4d0ec90ab/src/test.cpp:20:
  /tmp/pip-install-_7kaglg9/blspy_df253f728ad84f1d9b0290f4d0ec90ab/src/../contrib/catch/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
  10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
        |                                                          ^~~~~~~~~~~
  In file included from /usr/include/bits/sigstksz.h:24,
                   from /usr/include/signal.h:328,
                   from /tmp/pip-install-_7kaglg9/blspy_df253f728ad84f1d9b0290f4d0ec90ab/src/../contrib/catch/catch.hpp:8034,
                   from /tmp/pip-install-_7kaglg9/blspy_df253f728ad84f1d9b0290f4d0ec90ab/src/test.cpp:20:
  /usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
    640 | extern long int sysconf (int __name) __THROW;
        |                 ^~~~~~~
  In file included from /tmp/pip-install-_7kaglg9/blspy_df253f728ad84f1d9b0290f4d0ec90ab/src/test.cpp:20:
  /tmp/pip-install-_7kaglg9/blspy_df253f728ad84f1d9b0290f4d0ec90ab/src/../contrib/catch/catch.hpp:10881:45: error: size of array ‘altStackMem’ is not an integral constant-expression
  10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
        |                                             ^~~~~~~~~~~~
```

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by llowrey** [comment]
I submitted a PR to fix this: #291

**Comment by AmineKhaldi** [comment]
@llowrey thank you for sending a PR!

We actually came to that realization but thought to use this as a chance to properly leverage the Catch2 library into our build system, to not just fix the immediate issue but also be able to easily maintain it and seamlessly update it in the future.

The changes for that are being tested under different environments just to make sure nothing regresses, so stay tuned!

**Comment by llowrey** [comment]
Thanks for the update. I'll be looking for that new release but in the mean time is there a way I can get chia-blockchain to build with this new catch.hpp?

I'm not familiar with your build process and am not sure how to plug in my local bls-signatures build.

**Comment by AmineKhaldi** [comment]
Thanks to @altendky who created a wheels package for you and provided instructions on what you can try, here's what you can try:

* Grab the wheels from [here](https://github.com/Chia-Network/bls-signatures/suites/4346406112/artifacts/114022871) and install the appropriate wheel for your environment using something like `venv/bin/pip install ./x.whl`
* Comment out [this line](https://github.com/Chia-Network/chia-blockchain/blob/d2b6f28a3cca12ed0b7a47d09d1fb5717fc64bd9/setup.py#L5) as you'll be installing blspy manually from the above step.

I hope that helps, please let us know if you need anything.

**Comment by lklimek** [comment]
This can be also reproduced on Ubuntu 21.10 `impish` (most recent one), on main branch.

**Comment by AmineKhaldi** [comment]
@lklimek Could you please try PR #298 as that should address what you're seeing now?

**Comment by lklimek** [comment]
Ubuntu 21.10 builds correctly on the most recent `main` (1.0.8, commit 6385ba2a040ba011702cf1fa6e7785847abcf7a9). Thank you @AmineKhaldi

**Comment by emlowe** [comment]
Closing
