### ISSUE TITLE
add python tests

### ISSUE THREAD

**Issue by milahu** [Chia-Network/bls-signatures#300]
currently, there are no tests for python, if i see this right

maybe add one or two test cases?

```py
# bls-signatures/src/test.cpp Chia test vectors

import blspy

seed1 = 32 * b"\x00" # All 0s
sk1 = blspy.BasicSchemeMPL.key_gen(seed1)
assert str(sk1) == (
  "4a353be3dac091a0a7e640620372f5e1e2e4401717c1e79cac6ffba8f6905604"
)

pk1 = sk1.get_g1()
assert pk1.get_fingerprint() == 0xb40dd58a
assert str(pk1) == (
  "85695fcbc06cc4c4c9451f4dce21cbf8de3e5a13bf48f44cdbb18e2038ba7b8bb1632d7911e"
  "f1e2e08749bddbf165352"
)

message1 = b"\x07\x08\x09"
sig1 = blspy.BasicSchemeMPL.sign(sk1, message1)
assert str(sig1) == (
  "b8faa6d6a3881c9fdbad803b170d70ca5cbf1e6ba5a586262df368c75acd1d1f"
  "fa3ab6ee21c71f844494659878f5eb230c958dd576b08b8564aad2ee0992e85a"
  "1e565f299cd53a285de729937f70dc176a1f01432129bb2b94d3d5031f8065a1"
)
```

**Comment by mariano54** [comment]
Yes you may, that would be appreciated! Ideally we would have all the c++ test cases also in python.

**Comment by milahu** [comment]
> currently, there are no tests for python, if i see this right

seems i was blind

* [bls-signatures/python-bindings/test.py](https://github.com/Chia-Network/bls-signatures/blob/main/python-bindings/test.py)
* [bls-signatures/python-impl/impl-test.py](https://github.com/Chia-Network/bls-signatures/blob/main/python-impl/impl-test.py)

closing
