### ISSUE TITLE
verify

### ISSUE THREAD

**Issue by mircial** [Chia-Network/bls-signatures#330]
if i have a sig(48 bytes) and a pk (96 bytes), the dst is BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_. how can i use this api to verify?

**Comment by mircial** [comment]
could you provide op_swu_g1.py, just like op_swu_g2.py?

**Comment by mariano54** [comment]
This library is meant for 96 byte signatures and 48 byte pk. You need to do some work on the library to reverse that.
