### ISSUE TITLE
OSS-Fuzz: Validates invalid points

### ISSUE THREAD

**Issue by guidovranken** [Chia-Network/bls-signatures#331]
OSS-Fuzz report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47364

Regression range reported by OSS-Fuzz: https://github.com/Chia-Network/bls-signatures/compare/f2aa9ce14d84c1215953f87d2900312a864c7a65...51d89739a81e8aff5d3b2c2fe2d337d6e001ed60

```cpp
#include <relic_conf.h>
#include <bls.hpp>

int main(void)
{
    core_get();

    g1_t g1;
    g1_new(g1);
    g1_null(g1);
    RLC_TRY {
        fp_read_str(g1->x, "7", 1, 10);
    } RLC_CATCH_ANY {
        goto end;
    }

    RLC_TRY {
        fp_read_str(g1->y, "9", 1, 10);
    } RLC_CATCH_ANY {
        goto end;
    }

    fp_read_str(g1->z, "1", 1, 10);

    {
        try {
            /* FromNative calls CheckValid */
            const auto G1 = bls::G1Element::FromNative(g1);
            (void)G1;
            printf("Valid\n");
        } catch ( std::invalid_argument ) {
            printf("Invalid\n");
        }
    }

end:
    return 0;
}
```

**Comment by mariano54** [comment]
I believe this is fine, since FromNative now assumes that you have already created and validated the point separately (for optimization purposes). We should probably warn people that they shouldn't use this with untrusted input
