### ISSUE TITLE
C++ Compiler Error on Ubuntu Bionic release

### ISSUE THREAD

**Issue by jonspock** [Chia-Network/bls-signatures#4]
In file included from /usr/include/x86_64-linux-gnu/c++/7/bits/c++allocator.h:33:0,
                 from /usr/include/c++/7/bits/allocator.h:46,
                 from /usr/include/c++/7/string:41,
                 from /vagrant/bls-signatures/src/extendedpublickey.cpp:18:
/usr/include/c++/7/ext/new_allocator.h: In instantiation of ‘class __gnu_cxx::new_allocator<const BLSPublicKey>’:
/usr/include/c++/7/bits/allocator.h:108:11:   required from ‘class std::allocator<const BLSPublicKey>’
/usr/include/c++/7/bits/stl_vector.h:81:14:   required from ‘struct std::_Vector_base<const BLSPublicKey, std::allocator<const BLSPublicKey> >::_Vector_impl’
/usr/include/c++/7/bits/stl_vector.h:166:20:   required from ‘struct std::_Vector_base<const BLSPublicKey, std::allocator<const BLSPublicKey> >’
/usr/include/c++/7/bits/stl_vector.h:216:11:   required from ‘class std::vector<const BLSPublicKey>’
/vagrant/bls-signatures/src/aggregationinfo.hpp:108:32:   required from here
/usr/include/c++/7/ext/new_allocator.h:93:7: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(__gnu_cxx::new_allocator<_Tp>::const_reference) const [with _Tp = const BLSPublicKey; __gnu_cxx::new_allocator<_Tp>::const_pointer = const BLSPublicKey*; __gnu_cxx::new_allocator<_Tp>::const_reference = const BLSPublicKey&]’ cannot be overloaded
       address(const_reference __x) const _GLIBCXX_NOEXCEPT
       ^~~~~~~
/usr/include/c++/7/ext/new_allocator.h:89:7: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(__gnu_cxx::new_allocator<_Tp>::reference) const [with _Tp = const BLSPublicKey; __gnu_cxx::new_allocator<_Tp>::pointer = const BLSPublicKey*; __gnu_cxx::new_allocator<_Tp>::reference = const BLSPublicKey&]’
       address(reference __x) const _GLIBCXX_NOEXCEPT
       ^~~~~~~
/usr/include/c++/7/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::deallocate(__gnu_cxx::new_allocator<_Tp>::pointer, __gnu_cxx::new_allocator<_Tp>::size_type) [with _Tp = const BLSPublicKey; __gnu_cxx::new_allocator<_Tp>::pointer = const BLSPublicKey*; __gnu_cxx::new_allocator<_Tp>::size_type = long unsigned int]’:
/usr/include/c++/7/bits/alloc_traits.h:462:9:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::deallocate(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, std::allocator_traits<std::allocator<_CharT> >::pointer, std::allocator_traits<std::allocator<_CharT> >::size_type) [with _Tp = const BLSPublicKey; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<const BLSPublicKey>; std::allocator_traits<std::allocator<_CharT> >::pointer = const BLSPublicKey*; std::allocator_traits<std::allocator<_CharT> >::size_type = long unsigned int]’
/usr/include/c++/7/bits/stl_vector.h:180:19:   required from ‘void std::_Vector_base<_Tp, _Alloc>::_M_deallocate(std::_Vector_base<_Tp, _Alloc>::pointer, std::size_t) [with _Tp = const BLSPublicKey; _Alloc = std::allocator<const BLSPublicKey>; std::_Vector_base<_Tp, _Alloc>::pointer = const BLSPublicKey*; std::size_t = long unsigned int]’
/usr/include/c++/7/bits/stl_vector.h:162:22:   required from ‘std::_Vector_base<_Tp, _Alloc>::~_Vector_base() [with _Tp = const BLSPublicKey; _Alloc = std::allocator<const BLSPublicKey>]’
/usr/include/c++/7/bits/stl_vector.h:328:61:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = const BLSPublicKey; _Alloc = std::allocator<const BLSPublicKey>]’
/vagrant/bls-signatures/src/aggregationinfo.hpp:93:29:   required from here
/usr/include/c++/7/ext/new_allocator.h:125:19: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
  ::operator delete(__p);
  ~~~~~~~~~~~~~~~~~^~~~~
In file included from /usr/include/c++/7/ext/new_allocator.h:33:0,
                 from /usr/include/x86_64-linux-gnu/c++/7/bits/c++allocator.h:33,
                 from /usr/include/c++/7/bits/allocator.h:46,
                 from /usr/include/c++/7/string:41,
                 from /vagrant/bls-signatures/src/extendedpublickey.cpp:18:
/usr/include/c++/7/new:124:6: note:   initializing argument 1 of ‘void operator delete(void*)’
 void operator delete(void*) _GLIBCXX_USE_NOEXCEPT
      ^~~~~~~~
In file included from /usr/include/c++/7/vector:62:0,
                 from /vagrant/bls-signatures/src/blspublickey.hpp:20,
                 from /vagrant/bls-signatures/src/extendedpublickey.hpp:18,
                 from /vagrant/bls-signatures/src/extendedpublickey.cpp:19:
/usr/include/c++/7/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = const BLSPublicKey; _Args = {const BLSPublicKey&}]’:
/usr/include/c++/7/bits/stl_uninitialized.h:83:18:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const BLSPublicKey*, std::vector<const BLSPublicKey> >; _ForwardIterator = const BLSPublicKey*; bool _TrivialValueTypes = false]’
/usr/include/c++/7/bits/stl_uninitialized.h:134:15:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const BLSPublicKey*, std::vector<const BLSPublicKey> >; _ForwardIterator = const BLSPublicKey*]’
/usr/include/c++/7/bits/stl_uninitialized.h:289:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const BLSPublicKey*, std::vector<const BLSPublicKey> >; _ForwardIterator = const BLSPublicKey*; _Tp = const BLSPublicKey]’
/usr/include/c++/7/bits/stl_vector.h:331:31:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = const BLSPublicKey; _Alloc = std::allocator<const BLSPublicKey>]’
/vagrant/bls-signatures/src/aggregationinfo.hpp:93:29:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:13: error: invalid static_cast from type ‘const BLSPublicKey*’ to type ‘void*’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
             ^~~~~~~~~~~~~~~~~~~~~~~
'src/CMakeFiles/bls.dir/extendedpublickey.cpp.o' failed

**Comment by mariano54** [comment]
Looking into it

**Comment by mariano54** [comment]
It should work now with the latest commits. Also added a cmake build system as in your fork. Let me know if you have any suggestions for how to improve it.

**Comment by jonspock** [comment]
Great. Seems to be missing a CMakeLists.txt file in contrib/pybind11. If you guys have any kind of public Discord/Slack, please let me know. Feels weird chatting via Github issues.

**Comment by mariano54** [comment]
Yes we have a public keybase. Install keybase, and run this.
keybase team request-access chia_network.public

Also, pybind11 is a submodule so needs to be initalized.
