### ISSUE TITLE
Handle invalid public keys

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/bls-signatures#40]
When creating a PublicKey from bytes, an exception should be thrown instead of a relic error, if the public key is in the wrong format, or if the x coordinate has no valid y.

**Comment by codablock** [comment]
What will currently happen if an invalid public key is given to `PublicKey::FromBytes`?

**Comment by mariano54** [comment]
Relic error at g1_read_bin. We probably need to call CheckRelicErrors at the end of that method.
