### ISSUE TITLE
fatal error: bindings/blst.h: No such file or directory

### ISSUE THREAD

**Issue by kofi-dalvik** [Chia-Network/bls-signatures#434]
After following your build instructions and linking to my file, I got this error:

/usr/bin/g++ -std=c++11 -I../libs/bls-signatures/src -L../libs/bls-signatures/build/src -lbls -fdiagnostics-color=always -g /home/dahmed/libs/witenc/src/main.cpp -o /home/dahmed/libs/witenc/src/../out/main
In file included from ../libs/bls-signatures/src/privatekey.hpp:18,
                 from ../libs/bls-signatures/src/bls.hpp:18,
                 from /home/dahmed/libs/witenc/src/main.cpp:3:
../libs/bls-signatures/src/elements.hpp:19:10: fatal error: bindings/blst.h: No such file or directory
   19 | #include "bindings/blst.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

Please help, I don't know what to do next. 

OS:
ubuntu 22.04

**Comment by sehrixhshafeeq** [comment]
I am having the same error. Could you please how you resolved this issue ?

**Comment by hoffmang9** [comment]
I just attempted to replicate on a fresh install of Ubuntu 22.04.3 LTS.

I had to install:
```
sudo apt install build-essential
sudo apt install cmake
sudo apt install python3.10-dev
```
And that built and tested fine.
