### ISSUE TITLE
Support building on armv7l

### ISSUE THREAD

**Issue by PanderMusubi** [Chia-Network/bls-signatures#51]
Please, support building on armv7l. At the moment the build process stops at:

    Scanning dependencies of target relic_s
    [  3%] Building C object contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o
    In file included from /root/bls-signatures-20181101/contrib/relic/include/relic_arch.h:38:0,
                     from /root/bls-signatures-20181101/contrib/relic/include/relic_util.h:38,
                     from /root/bls-signatures-20181101/contrib/relic/include/relic_err.h:42,
                     from /root/bls-signatures-20181101/contrib/relic/include/relic_core.h:43,
                     from /root/bls-signatures-20181101/contrib/relic/src/relic_err.c:36:
    /root/bls-signatures-20181101/contrib/relic/include/relic_types.h:112:9: error: unknown type name ‘__uint128_t’
     typedef __uint128_t dbl_t;
             ^~~~~~~~~~~
    contrib/relic/src/CMakeFiles/relic_s.dir/build.make:62: recipe for target 'contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o' failed
    make[2]: *** [contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o] Error 1
    CMakeFiles/Makefile2:136: recipe for target 'contrib/relic/src/CMakeFiles/relic_s.dir/all' failed
    make[1]: *** [contrib/relic/src/CMakeFiles/relic_s.dir/all] Error 2

This is blocking building of Dash, see https://github.com/dashpay/dash/issues/2562

**Comment by codablock** [comment]
This seems to be not an issue with this library but rather an issue with the build system in Dash. This is being fixed atm. @PanderMusubi I think you can close this issue.
