### ISSUE TITLE
blspy: raises exception on bad PrependSignature

### ISSUE THREAD

**Issue by richardkiss** [Chia-Network/bls-signatures#65]
This code raises an exception instead of returning False.

```
import blspy

private_key = blspy.ExtendedPrivateKey.from_seed(b"foo").get_private_key()

message_hash = bytes([9] * 32)

sig = private_key.sign_prepend_prehashed(message_hash).serialize()
sig = sig[:-1] + bytes([0])

public_key = private_key.get_public_key()

bad_signature = blspy.PrependSignature.from_bytes(sig[:-1] + bytes([0]))

# the next line raises 
# FATAL ERROR in relic_ep2_util.c:282

bad_signature.verify([message_hash], [public_key])
```

**Comment by mariano54** [comment]
For me the code is failing in  bad_signature = blspy.PrependSignature.from_bytes(sig[:-1] + bytes([0])).
Can you check if that's where it fails for you? It should throw an exception because it's not a valid curve point.

**Comment by richardkiss** [comment]
You are correct, it is the from_bytes call. The comment is wrong.

There are two problems here:

1. It prints `FATAL ERROR in relic_ep2_util.c:282`, polluting standard out.

2. It raises a `RuntimeError`, which seems out of place – maybe a `ValueError`, or a subclass of it,, or nothing at all, and simply returning "false" at the `verify` call. How could we know that this is an invalid signature before making this call? Most use cases don't care why it's invalid (wrong size, not a valid point, valid point but wrong value), only that it is invalid.

**Comment by mariano54** [comment]
Changed to a ValueError and removed the printing
