### ISSUE TITLE
Npm PrivateKey.fromSeed not working at all

### ISSUE THREAD

**Issue by janus** [Chia-Network/bls-signatures#67]
Trying to run the node example, but PrivateKey.fromSeed fails with the below error message
```const { PrivateKey } = require('bls-signatures');
const privateKey = PrivateKey.fromSeed(Uint8Array.from([1,2,3]));
const sig = privateKey.sign(Uint8Array.from(Buffer.from("Hello world!")));```

FATAL ERROR in relic_rand_core.c:110
FATAL ERROR in relic_rand_core.c:110
FATAL ERROR in relic_rand_core.c:110
FATAL ERROR in relic_rand_core.c:110
FATAL ERROR in relic_rand_core.c:110
FATAL ERROR in relic_rand_core.c:110
FATAL ERROR in relic_rand_core.c:110
FATAL ERROR in relic_rand_core.c:110

**Comment by mariano54** [comment]
@antouhou Can you take a look at this?

**Comment by antouhou** [comment]
Oh wow, didn't see that a year ago :D It looks like a lot happened to the lib since then. On any of my build machines, the tests are passing perfectly fine. I've published a new version of bindings to the npm, so it might fix the issue. I'm not sure if this issue still is relevant

**Comment by emlowe** [comment]
Closing on the assumption this doesn't happen anymore
