### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by jannikluhn** [Chia-Network/bls-signatures#68]
I'm trying to build the library using the steps described in the readme, but it fails with the following error message:

```
[ 97%] Building CXX object src/CMakeFiles/runbench.dir/test-bench.cpp.o
/usr/bin/ar: /usr/lib/libgmp.so: file format not recognized
make[2]: *** [src/CMakeFiles/combined_custom.dir/build.make:60: src/CMakeFiles/combined_custom] Error 1
make[1]: *** [CMakeFiles/Makefile2:312: src/CMakeFiles/combined_custom.dir/all] Error 2
```

OS is Arch Linux. `libgmp.so` seems to come from version 6.1.2-2 of this package: https://www.archlinux.org/packages/core/x86_64/gmp/ (which was already installed on my machine).

**Comment by mariano54** [comment]
This library uses your installed GMP if it's available, otherwise it just uses relic arithmetic which is slower. I have not tested compilation on arch though. 

Can you try reinstalling GMP in arch (or updating)?
Or you can just not use GMP, by changing the compilation settings:
https://github.com/Chia-Network/bls-signatures/blob/master/CMakeLists.txt#L29

This will make the library a little slower.

**Comment by jannikluhn** [comment]
GMP is up to date already and reinstalling didn't help. I went with disabling it in `CMakeLists.txt` and got a similar error for `libsodium.so` ([package](https://www.archlinux.org/packages/community/x86_64/libsodium/)):

```
/usr/bin/ar: /usr/lib/libsodium.so: file format not recognized
make[2]: *** [src/CMakeFiles/combined_custom.dir/build.make:60: src/CMakeFiles/combined_custom] Error 1
make[1]: *** [CMakeFiles/Makefile2:312: src/CMakeFiles/combined_custom.dir/all] Error 2
```

After disabling `libsodium` as well, compilation succeeds, so I'm happy for now. Thank you!

Leaving this issue open though as it's only a workaround.

**Comment by jannikluhn** [comment]
The problem seems to be that `libgmp.so` and `libsodium.so` are dynamic libraries, not static ones. Arch only provides the former, not the latter.
