### ISSUE TITLE
Gorbonov's Same Message Attack

### ISSUE THREAD

**Issue by ChristopherA** [Chia-Network/bls-signatures#7]
Are the pairing aggregate signatures vulnerable to Sergey Gorbunov's attack "an adversary can carefully craft a public key PK_2 such that his signature alone would suffice to fake an aggregate signature!" as described in https://medium.com/@sergey_nog/how-not-to-use-aggregate-signatures-in-your-blockchain-63e05be2cbbe ?

**Comment by mariano54** [comment]
No, it's not vulnerable. Each public key / signature is raised to a specific power, computed from H(all public keys). This means that any pk the attacker crafts, will be raised to a specific power (also the victims keys), and thus he cannot craft such a key.

That's the beauty of this construction, which allows you to combine pubic keys and signatures, and get efficient verification (only one pairing per message). So if you have 500 signatures on m1 and 500 signatures on m2, and you combine them all, verifying the aggregate signature requires only 2 pairing operations. This is helpful in scenarios where same message is used, like combining inputs and signing an identical transaction.

The cost is that the code is a little more complex, aggregation is more expensive, and we need to keep track of the tree of aggregates and what that looks like.
