### ISSUE TITLE
Signature::DivideBy maybe speed up.

### ISSUE THREAD

**Issue by mogisawa** [Chia-Network/bls-signatures#71]
In `Signature::DivideBy`, mod inversion `fp_inv_exgcd_bn` is called `pks.size()` times in each `divisorSigs`.
When `i>0`, `inverted` is used only checking `quotient` and `divisor` and `dividend` of i-th, as a equation;
`quotient == dividend[i] / divisor[i] mod ord`.
Same check is can be done by following;
`quotient * divisor[i] = dividend[i] mod ord`
It needs no inversion.

**Comment by mogisawa** [comment]
Please see commit af6b30d.
Other commits are my mistakes...

**Comment by mariano54** [comment]
Thanks! Have you tested to see if it gives a speed up?

**Comment by mogisawa** [comment]
I tried it. I did the following bench test.
```
void benchDivideBy() {
    double numIters = 1000;
    uint8_t message[32];
    uint8_t seed[32];

    getRandomSeed(seed);
    PrivateKey sk = PrivateKey::FromSeed(seed, sizeof(seed));

    std::vector<Signature> sigs1;
    std::vector<Signature> sigs2;
    for (size_t i = 0; i < numIters; i++) {
        getRandomSeed(message);
        Signature sig = sk.Sign(message, sizeof(message));
        sigs1.push_back(sig);
        sigs2.push_back(sig);
    }

    // Divide by aggregate
    Signature aggSig1 = Signature::Aggregate(sigs1);
    std::vector<PublicKey> pubkeys = aggSig1.GetAggregationInfo()->GetPubKeys();
    std::vector<uint8_t*> hashes = aggSig1.GetAggregationInfo()->GetMessageHashes();
    std::vector<bn_t*> exponents;
    bn_t ord;
    g2_get_ord(ord);
    bn_t m;
    bn_new(m);
    bn_rand_mod(m, ord);
    for (size_t i = 0; i < pubkeys.size(); i++) {
        bn_t exp;
        bn_new(exp);
        aggSig1.GetAggregationInfo()->GetExponent(&exp, hashes[i], pubkeys[i]);
        bn_mul(exp, exp, m);
        exponents.push_back(&exp);
    }
    Signature aggSig2 = Signature::Aggregate(sigs2);
    aggSig2.SetAggregationInfo(AggregationInfo::FromVectors(pubkeys, hashes, exponents));
    Signature aggSig3 = Signature::Aggregate(std::vector<Signature>{aggSig1});
    std::vector<Signature> divisor = {aggSig2};
    auto start = startStopwatch();
    aggSig3.DivideBy(divisor);
    endStopwatch("DivideBy", start, numIters);
}
```
I also confirmed that the number of pks was 1000, and the number of calling of inverse was reduced from 1000 to 1.
Please note that the exponents of AggregationInfo are recreated by applying a random number.
Because I expected that if all of the exponent of divisorSig is 1, there is not much difference.
(codes around exponents were few difficult for me...)
The result is here.
<Before speed up>
```
DivideBy
Total: 1000 runs in 61 ms
Avg: 0.061 ms
```
<After speed up>
```
DivideBy
Total: 1000 runs in 39 ms
Avg: 0.039 ms
```
About 36% reduced. I tried it a few times, and the result was similar.

**Comment by mariano54** [comment]
Excellent, could you create a simple PR with the change?
Thanks!

**Comment by mogisawa** [comment]
Grad! Yes. See #74 PR. Thanks!
