### ISSUE TITLE
Where is relic_conf.h ?

### ISSUE THREAD

**Issue by hjlee9182** [Chia-Network/bls-signatures#84]
I write this code " #inlucde "../src/bls.hpp"   " another .cpp file.
![에러하나](https://user-images.githubusercontent.com/46337218/68863214-45430200-0732-11ea-9206-e8acb36eb58d.PNG)

But this error occur.
How to fix it?

**Comment by mariano54** [comment]
In the readme it explains which include files to use, have you done this?

g++ -Wl,-no_pie  -Ibls-signatures/contrib/relic/include -Ibls-signatures/build/contrib/relic/incl
ude -Ibls-signatures/src/  -L./bls-signatures/build/ -l bls  yourfile.cpp

**Comment by hjlee9182** [comment]
@mariano54 
When I did input "make" , I want to this code is automatically implement.
Do you know how to add this code?

**Comment by mariano54** [comment]
Sorry I'm not sure what you mean. Instructions on how to build are in the readme. Include files are the in the directories from my previous comment.

**Comment by BekzhanOmirzak** [comment]
> In the readme it explains which include files to use, have you done this?
> 
> g++ -Wl,-no_pie -Ibls-signatures/contrib/relic/include -Ibls-signatures/build/contrib/relic/incl ude -Ibls-signatures/src/ -L./bls-signatures/build/ -l bls yourfile.cpp

Sorry, I didn't understand could give more details?
