### ISSUE TITLE
I have a problem!

### ISSUE THREAD

**Issue by hjlee9182** [Chia-Network/bls-signatures#85]
![에러하나](https://user-images.githubusercontent.com/46337218/68929398-a5d44c80-07cf-11ea-8e4a-ab4d8257d6a3.PNG)
![fle](https://user-images.githubusercontent.com/46337218/68929429-b71d5900-07cf-11ea-9f76-f7d9d4f4c12a.PNG)
I follow the code in Readme . 
build and run
But this error occured. How to fix this problem???

**Comment by mariano54** [comment]
You need to compile your file with c++ 11:
g++ -std=c++11 .............

**Comment by hjlee9182** [comment]
![에러둘](https://user-images.githubusercontent.com/46337218/68965962-5d914a80-0820-11ea-81b4-43118a2a29c5.PNG)
I follow your suggestion.
Now this error occured.

**Comment by hoffmang9** [comment]
https://askubuntu.com/questions/346377/cannot-find-lgcc-s

**Comment by hjlee9182** [comment]
@hoffmang9 
Still doesn't work...
I think that's symbolic link problem. How about you?

**Comment by khow11** [comment]
@hjlee9182 
I encountered the same problem, "/usr/bin/ld: cannot find -lgcc_s".

I think it is caused by the "-Wl, -no_pie" and "-lbls", because my g++ works well for other program compilation without using bls. But I have no idea how to solve it.

Any help? Thank you.

**Comment by hoffmang9** [comment]
@khow11 
Which OS and version? What version of cmake? What version of gcc?

What is the output of:
`sudo find / -name libgcc_s.so -print`

**Comment by khow11** [comment]
@hoffmang9 
Ubuntu 16.04.6 LTS, g++ 5.4.0, cmake 3.5.1

the output of "sudo find / -name libgcc_s.so -print" is:

/lib64/libgcc_s.so
/usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc_s.so
/usr/lib/gcc/x86_64-linux-gnu/5/libgcc_s.so
/usr/lib/libgcc_s.so
find: ‘/run/user/112/gvfs’: Permission denied

they are all links to "/lib/x86_64-linux-gnu/libgcc_s.so.1"

Thank you for any clue to solve this!

**Comment by hoffmang9** [comment]
Add the path to the library to your compile command with `-L/lib/x86_64-linux-gnu/libgcc_s.so.1`:

`g++ -Wl,-no_pie  -Ibls-signatures/contrib/relic/include -Ibls-signatures/build/contrib/relic/include -Ibls-signatures/src/  -L/lib/x86_64-linux-gnu/libgcc_s.so.1 -L./bls-signatures/build/ -l bls  yourfile.cpp
`

That works for me on a test install of Ubuntu 16.04.6 LTS, with g++ 5.4.0, cmake 3.5.1.

The [link above](https://github.com/Chia-Network/bls-signatures/issues/85#issuecomment-554482879) to askubuntu had this answer also.

**Comment by Gauthamastro** [comment]
> Add the path to the library to your compile command with `-L/lib/x86_64-linux-gnu/libgcc_s.so.1`:
> 
> `g++ -Wl,-no_pie -Ibls-signatures/contrib/relic/include -Ibls-signatures/build/contrib/relic/include -Ibls-signatures/src/ -L/lib/x86_64-linux-gnu/libgcc_s.so.1 -L./bls-signatures/build/ -l bls yourfile.cpp `
> 
> That works for me on a test install of Ubuntu 16.04.6 LTS, with g++ 5.4.0, cmake 3.5.1.
> 
> The [link above](https://github.com/Chia-Network/bls-signatures/issues/85#issuecomment-554482879) to askubuntu had this answer also.

This didn't work for me its the same error
![Error](https://user-images.githubusercontent.com/17110878/73134163-693b9180-4059-11ea-8f57-e4254640787a.JPG)

**Comment by hoffmang9** [comment]
What was the output of `sudo find / -name libgcc_s.so -print`? Does `/lib/x86_64-linux-gnu/libgcc_s.so.1` exist on your machine?

The error you're seeing is that g++ can't find libgcc_s.so on your machine so you need to tell it where to find it and you can't blindly follow what was recommended for someone else's machine.

-Gene

**Comment by Gauthamastro** [comment]
> sudo find / -name libgcc_s.so -print

The Output is the above command is,
```
/usr/lib/gcc/libgcc_s.so
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so
/home/gautham/anaconda3/lib/libgcc_s.so
/home/gautham/anaconda3/pkgs/libgcc-ng-9.1.0-hdf63c60_0/lib/libgcc_s.so
```
libgcc_s.so.1 exists on this /lib/x86_64-linux-gnu//5.4.0/ folder.

**Comment by hoffmang9** [comment]
so try: `g++ -Wl,-no_pie -Ibls-signatures/contrib/relic/include -Ibls-signatures/build/contrib/relic/include -Ibls-signatures/src/ -L/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so -L./bls-signatures/build/ -l bls yourfile.cpp` and if that doesn't work, try each of the three other versions you have on your machine.
