### ISSUE TITLE
/usr/bin/ld: cannot find -lgcc_s Cannot find 

### ISSUE THREAD

**Issue by Gauthamastro** [Chia-Network/bls-signatures#88]
![Error](https://user-images.githubusercontent.com/17110878/73133523-cfbbb200-404f-11ea-9e12-5c0a42c32655.JPG)
![main_image](https://user-images.githubusercontent.com/17110878/73133531-e95cf980-404f-11ea-8eef-c290f5964cd5.JPG)

I am trying to compile and I get this error.  I have already tested with other CPP files and g++ compiles just fine. Can someone help me with what I am doing wrong here?

**Comment by yaoya0111** [comment]
i have same situation.

**Comment by hoffmang9** [comment]
Check this? - https://askubuntu.com/questions/346377/cannot-find-lgcc-s

**Comment by yaoya0111** [comment]
i try to solve it but didn't work. they said problem is the `libgcc_s.so` link to other `libgcc_s`. 

---------------

this is my gcc config
`$ gcc -v`
 output:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```
-------------

i use `$ find /usr/ -name "libgcc_s*" ` to get this:
```
/usr/lib/x86_64-linux-gnu/libgcc_s.so.1
/usr/lib/x86_64-linux-gnu/libgcc_s.so
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so.1
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so
/usr/lib/libgcc_s.so
/usr/lib32/libgcc_s.so.1
```
the file `/usr/lib/libgcc_s.so` and `/usr/lib/x86_64-linux-gnu/libgcc_s.so` are created by myself,  both linked to `/lib/x86_64-linux-gnu/libgcc_s.so.1` and use `sudo ldconfig` to reload.

--------

then go to directory ` /root/work/bls-signatures/build/`, commad this to compile
`g++ -Wl,-no_pie -std=c++14  -I ./_deps/relic-src/include -I ./_deps/relic-build/include -I ../src -L. -lbls test.cpp`

the `test.cpp` content is copy from project `readme.md`

i still get error `/usr/bin/ld: cannot find -lgcc_s, /usr/bin/ld: cannot find -lgcc_s`

**Comment by hoffmang9** [comment]
What is `uname -a`? Are you on a 64 Bit 18.04 LTS?

**Comment by yaoya0111** [comment]
yes.
`uname -a` 
get this
`Linux 6488a6c8b7b0 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by hoffmang9** [comment]
You can try `-static-libgcc` but googling around shows that there were these kinds of issues with gcc in that era on 16.04. I'd suggest updating your compiler if the flag above doesn't help.

**Comment by yaoya0111** [comment]
thanks
