### ISSUE TITLE
Where do you prefer discussions…

### ISSUE THREAD

**Issue by ChristopherA** [Chia-Network/bls-signatures#9]
Some place in the README.md there should be some mention of the best place to have discussions about your bls-signatures library. A mailing list, a forum, or this issues repo.

While you are at it you probably you should also talk about requirement for contributions and pull requests.

**Comment by RyanSinger** [comment]
The best place for discussion is our keybase channel.

https://keybase.io/team/chia_network.public

**Comment by ChristopherA** [comment]
Ouch, yet another group channel. I currently have email, many separate slacks, rocket.chat, signal, messenger, telegram, and a number of discourse forums. Not your fault, but at least with email lists I can read without being a member.

**Comment by RyanSinger** [comment]
I understand. Right now we have over 2k people involved on keybase, so it'd
be hard to move. Enjoy hacking on the library!

Ryan

**Comment by mariano54** [comment]
Added section in the readme.
