### ISSUE TITLE
Does not work on 32 bit system

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/bls-signatures#90]
Relic should be compiled with WSIZE = 32 for 32 bit systems, right now it's defaulting to 64.

  In file included from /tmp/pip-install-n6sj5xwf/blspy/contrib/relic/include/relic_arch.h:38,
                   from /tmp/pip-install-n6sj5xwf/blspy/contrib/relic/include/relic_util.h:38,
                   from /tmp/pip-install-n6sj5xwf/blspy/contrib/relic/include/relic_err.h:42,
                   from /tmp/pip-install-n6sj5xwf/blspy/contrib/relic/include/relic_core.h:43,
                   from /tmp/pip-install-n6sj5xwf/blspy/contrib/relic/src/relic_err.c:36:
  /tmp/pip-install-n6sj5xwf/blspy/contrib/relic/include/relic_types.h:112:9: error: unknown type name ‘__uint128_t’
   typedef __uint128_t dbl_t;

**Comment by antouhou** [comment]
You can change the WSIZE manually in https://github.com/Chia-Network/bls-signatures/blob/master/CMakeLists.txt#L43
