### ISSUE TITLE
How to compile on a raspberry pi (4)?

### ISSUE THREAD

**Issue by WillWammer** [Chia-Network/bls-signatures#95]
Installing chia with the usual commands returns the following error. This is after running 'make'.

`[  0%] Built target arith_objs
[  0%] Building C object contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o
In file included from /home/pi/bls-signatures-20181101/contrib/relic/include/relic_arch.h:38,
                 from /home/pi/bls-signatures-20181101/contrib/relic/include/relic_util.h:40,
                 from /home/pi/bls-signatures-20181101/contrib/relic/include/relic_err.h:42,
                 from /home/pi/bls-signatures-20181101/contrib/relic/include/relic_core.h:43,
                 from /home/pi/bls-signatures-20181101/contrib/relic/src/relic_err.c:36:
/home/pi/bls-signatures-20181101/contrib/relic/include/relic_types.h:112:9: error: unknown type name ‘__uint128_t’
 typedef __uint128_t dbl_t;
         ^~~~~~~~~~~
make[2]: *** [contrib/relic/src/CMakeFiles/relic_s.dir/build.make:63: contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: contrib/relic/src/CMakeFiles/relic_s.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

Been working on this for a while now, I've installed countless libraries to try to fix this. Works perfectly fine on a 64 bit OS.

**Comment by hoffmang9** [comment]
This library does not currently compile on anything but 64 bit operating systems. It works fine on 64 but Ubuntu on Pi 4 for example.

**Comment by WillWammer** [comment]
@hoffmang9 Ah ok thanks, I'll load a 64 bit OS! Thanks a lot for your quick reply!
